WITH DISCOUNT AS (
    SELECT CAR_TYPE,(1 - (DISCOUNT_RATE * 0.01)) AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상')

SELECT CAR_ID, CAR_TYPE, ROUND(30 * DAILY_FEE * RATE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN DISCOUNT D USING (CAR_TYPE)
WHERE CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01') 
    AND CAR_TYPE IN ('세단', 'SUV')
    AND ROUND(30 * DAILY_FEE * RATE) >= 500000
    AND ROUND(30 * DAILY_FEE * RATE) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
