WITH CAR_AND_RENTAL_HISTORY AS (
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DUR_TIME,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL 
        END AS DURATION_TYPE
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN 
        CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE 
        C.CAR_TYPE = '트럭'
)
SELECT 
    CR.HISTORY_ID,
    CASE 
        WHEN CR.DURATION_TYPE IS NULL THEN CR.DAILY_FEE * CR.DUR_TIME
        ELSE TRUNCATE(CR.DAILY_FEE * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100) * CR.DUR_TIME, 0)
    END AS FEE
FROM 
    CAR_AND_RENTAL_HISTORY CR 
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = '트럭' AND CR.DURATION_TYPE = P.DURATION_TYPE
ORDER BY 
    FEE DESC, CR.HISTORY_ID DESC;